- name: Gather the package facts
  package_facts:
    manager: auto

- name: Set architecture for audit tasks
  set_fact:
    audit_arch: b64
  when:
  - '"audit" in ansible_facts.packages'
  - ansible_architecture == "x86_64"

# Record Events that Modify the System's Discretionary Access Controls
- include_tasks: record-dac-changes.yml
  vars:
    syscalls:
      - chmod
      - fchmod
      - fchmodat
    syscall_grouping:
      - chmod
      - fchmod
      - fchmodat

- include_tasks: record-dac-changes.yml
  vars:
    syscalls:
      - chown
      - fchown
      - fchownat
      - lchown
    syscall_grouping:
      - chown
      - fchown
      - fchownat
      - lchown

- include_tasks: record-dac-changes.yml
  vars:
    syscalls:
      - fremovexattr
      - fsetxattr
      - lremovexattr
      - lsetxattr
    syscall_grouping:
      - fremovexattr
      - lremovexattr
      - removexattr
      - fsetxattr
      - lsetxattr
      - setxattr

- include_tasks: record-dac-changes.yml
  vars:
    syscalls:
      - removexattr
      - setxattr
    syscall_grouping:
      - fremovexattr
      - lremovexattr
      - removexattr
      - fsetxattr
      - lsetxattr
      - setxattr

- include_tasks: record-dac-changes.yml
  vars:
    syscalls:
      - umount
      - umount2
    syscall_grouping: []

# Record xecution Attempts to Run ACL Privileged Commands
- include_tasks: record-acl-priv-commands.yml

# Record Execution Attempts to Run SELinux Privileged Commands
- include_tasks: record-selinux-priv-commands.yml

# Record File Deletion Events by User
- include_tasks: record-user-file-deletion.yml

# Record Unauthorized Access Attempts Events to Files (unsuccessful)
- include_tasks: record-unauth-file-access.yml

# Record Information on Kernel Modules Loading and Unloading
- include_tasks: record-kernel-module.yml

# Record Attempts to Alter Logon and Logout Events
- include_tasks: record-login-out.yml

# Record Information on the Use of Privileged Commands
- include_tasks: record-priv-commands.yml
  vars:
    selinux_item_path: "{{ item }}"
  loop:
    - /usr/sbin/init
    - /usr/sbin/poweroff
    - /usr/sbin/reboot
    - /usr/sbin/shutdown
    - /usr/bin/chage
    - /usr/bin/chsh
    - /usr/bin/crontab
    - /usr/bin/gpasswd
    - /usr/bin/kmod
    - /usr/bin/mount
    - /usr/bin/newgrp
    - /usr/sbin/pam_timestamp_check
    - /usr/bin/passwd
    - /usr/sbin/postdrop
    - /usr/sbin/postqueue
    - /usr/libexec/openssh/ssh-keysign
    - /usr/bin/su
    - /usr/bin/sudo
    - /usr/bin/sudoedit
    - /usr/bin/umount
    - /usr/sbin/unix_chkpwd
    - /usr/sbin/unix_update
    - /usr/sbin/userhelper
    - /usr/sbin/usermod
    - /usr/bin/ssh-agent

- include_tasks: record-user-group-changes.yml
  vars:
    selinux_item_to_monitor: "{{ item }}"
  loop:
    - /etc/group
    - /etc/gshadow
    - /etc/security/opasswd
    - /etc/passwd
    - /etc/shadow