---
- name: Add influxdb yum.repo config
  copy: src=influxdb-rhel7.repo dest="/etc/yum.repos.d/influxdb.repo" owner=root group=root mode=644
  when: ansible_distribution_major_version|int == 7

- name: Add influxdb yum.repo config
  copy: src=influxdb-rhel8.repo dest="/etc/yum.repos.d/influxdb.repo" owner=root group=root mode=644
  when: ansible_distribution_major_version|int > 7
  
- name: Install InfluxDB
  yum: name=influxdb state=present

- name: Add Firewall Zone
  firewalld: zone="{{influxdb_firewalld_zone}}" state=present permanent=yes

- name: Reload Firewalld
  service: name=firewalld state=reloaded

- name: Add Sources
  firewalld: zone="{{ influxdb_firewalld_zone }}" source="{{item}}" state=enabled permanent=yes immediate=yes
  loop: "{{ influxdb_firewalld_source_ips }}"

- name: Add Ports
  firewalld: zone="{{ influxdb_firewalld_zone }}" port="{{ influxdb_firewalld_port }}/tcp" state=enabled permanent=yes immediate=yes

- name: Ensure influxdb is enabled and started
  service: name=influxdb enabled=yes state=started

