---
- name: Add MySQL exporter user
  mysql_user: name="{{prometheus_mysqld_exporter_username}}" password="{{prometheus_mysqld_exporter_password}}" login_user=root login_password="{{mysql_root_password}}" priv="*.*:PROCESS,REPLICATION CLIENT,SELECT,SLAVE MONITOR"

- name: Install golang-prometheus-mysqld-exporter
  yum: name=golang-github-prometheus-mysqld-exporter state=present

- name: Update mysql.cnf user
  ini_file: dest=/etc/prometheus/mysqld_exporter/mysql.cnf section=client option=user value="{{prometheus_mysqld_exporter_username}}"

- name: Update mysql.cnf password
  ini_file: dest=/etc/prometheus/mysqld_exporter/mysql.cnf section=client option=password value="{{prometheus_mysqld_exporter_password}}"

- name: Update listening config
  lineinfile:
    path: /etc/sysconfig/prometheus-mysqld-exporter
    regexp: '^PROMETHEUS_MYSQLD_EXPORTER_LISTEN='
    line: "PROMETHEUS_MYSQLD_EXPORTER_LISTEN={{prometheus_mysqld_exporter_listen}}:{{prometheus_mysqld_exporter_firewalld_port}}"

- name: Ensure systemd sees the service
  systemd: daemon_reload=yes

- name: Remove Deprecated Firewall Zone
  ansible.builtin.firewalld:
    zone: prometheus-access
    state: absent
    permanent: yes

- name: Allow access through firewall to prometheus exporter port
  ansible.builtin.firewalld:
    zone: "{{prometheus_mysqld_exporter_firewalld_zone}}"
    permanent: true
    immediate: true
    state: enabled
    rich_rule: "rule family=ipv4 source address={{item}} port port={{prometheus_mysqld_exporter_firewalld_port}} protocol=tcp accept"
  loop: "{{ prometheus_firewalld_source_ips }}"

- name: Ensure prometheus-mysqld-exporter is enabled and started
  service: name=prometheus-mysqld-exporter enabled=yes state=started

