---
- name: Gather the package facts
  package_facts:
    manager: auto

- name: Install libselinux-python
  ansible.builtin.dnf: name=libselinux-python state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int <= 7

- name: Install libselinux-python
  ansible.builtin.dnf: name=python3-libselinux state=present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

- name: Install default configured packages
  ansible.builtin.dnf: name="{{ item }}" state=present
  loop: "{{ packages_default_packages }}"

- name: Enable haveged service
  service: name=haveged state=started enabled=yes

- name: Install additionally configured packages
  ansible.builtin.dnf: name="{{ item }}" state=present
  loop: "{{ packages_additional_packages }}"

- name: Update all packages to latest version
  ansible.builtin.dnf: name=* state=latest
  when: ansible_os_family == "RedHat"
  notify:
    - update aide

