---
backup_server_target_user: root
backup_server_hourly: 24
backup_server_daily: 7
backup_server_weekly: 5
backup_server_monthly: 3
backup_server_include:
  - /*
backup_server_exclude:
  - /sys
  - /proc
  - /tmp
  - /dev
  - /var/lib/libvirt/images
  - /var/lock
  - /var/run
  - /run
  - /srv/rsnapshot

backup_server_directory: /srv/rsnapshots
backup_server_systemd_services:
  - rsnapshot-daily@.service
  - rsnapshot-hourly@.service
  - rsnapshot-weekly@.service
  - rsnapshot-monthly@.service
