---
- name: Install app_dev.conf
  copy: src=app_dev.conf dest=/etc/httpd/conf.d/app_dev.conf

- name: Create passwd
  file: path=/etc/httpd/passwd state=directory owner=root group=root mode=755

- name: include passlib
  yum: pkg=python-passlib state=present

- name: Add htpasswd users
  htpasswd: name=gnat password=19mada98 state=present path=/etc/httpd/passwd/symfony-dev
  notify:
    - update aide

- name: Include wkhtmltopdf
  stat: path=/usr/local/bin/wkhtmltopdf
  register: st_wkhtmltopdf

- name: Install wkhtmltopdf
  yum: pkg=http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos{{ansible_distribution_major_version}}-amd64.rpm state=present
  when: st_wkhtmltopdf.stat.exists
