---
- name: Ensure iptables is installed
  yum: pkg=iptables state=present

- name: Install iptables config
  template: src=iptables.j2 dest=/etc/sysconfig/iptables

- name: Enable iptables
  service: name=iptables enabled=yes
  notify: restart iptables
