---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install, configure, and start nginx prometheus-exporter
  when: "'nginx' in ansible_facts.packages"
  block:
    - name: Install nginx-exporter
      yum: name=golang-github-nginxinc-nginx-prometheus-exporter state=present

    - name: Install nginx status config
      template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/99-nginx-status.conf owner=root group=root mode=0644

    - name: Update sysconfig - listen address
      lineinfile:
        path: /etc/sysconfig/prometheus-nginx-exporter
        regexp: '^LISTEN_ADDRESS='
        line: "LISTEN_ADDRESS={{prometheus_nginx_exporter_listen}}:{{prometheus_nginx_exporter_firewalld_port}}"

    - name: Update sysconfig - scrape uri
      lineinfile:
        path: /etc/sysconfig/prometheus-nginx-exporter
        regexp: '^SCRAPE_URI='
        line: "SCRAPE_URI={{prometheus_nginx_exporter_scrape_uri}}"

    - name: Ensure systemd sees the service
      systemd: daemon_reload=yes

    - name: Remove Deprecated Firewall Zone
      ansible.builtin.firewalld:
        zone: prometheus-access
        state: absent
        permanent: yes

    - name: Allow access through firewall to prometheus exporter port
      ansible.builtin.firewalld:
        zone: "{{prometheus_nginx_exporter_firewalld_zone}}"
        permanent: true
        immediate: true
        state: enabled
        rich_rule: "rule family=ipv4 source address={{item}} port={{prometheus_nginx_exporter_firewalld_port}} protocol=tcp"
      loop: "{{ prometheus_firewalld_source_ips }}"

    - name: Ensure nginx is enabled and reloaded
      service: name=nginx enabled=yes state=reloaded

    - name: Ensure prometheus-nginx-exporter is enabled and started
      service: name=prometheus-nginx-exporter enabled=yes state=restarted

