—-
- name: PHP | PHPDev | Install composer
  command: curl -sS https://getcomposer.org/installer | /usr/bin/php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer

- name: Install composer wrapper
  copy: dest=/usr/local/bin/composer owner=root group=owner mode=755 src=composer

- name: PHP | PHPDev | Update composer
  command: /usr/local/bin/composer self-update
  notify:
    - update aide

