---
- name: Install git
  yum: pkg=git state=present

- name: PHP | PHPDev | Install composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer.phar

- name: Install composer wrapper
  copy: src=composer dest=/usr/local/bin/composer owner=root group=root mode=755

- name: Ensure Permisions
  file: path=/usr/local/bin/composer.phar owner=root group=root mode=755

- name: PHP | PHPDev | Update composer
  command: /usr/local/bin/composer self-update
  notify:
    - update aide
