---
- name: Install php-fpm-exporter
  yum: name=golang-github-hipages-php-fpm-exporter state=present

- name: Configure prometheus-php-fpm-exporter systemd Group parameter
  file: path=/etc/systemd/system/prometheus-php-fpm-exporter.service.d state=directory mode=0755

- name: Install systemd drop in
  template: src=group.conf.j2 dest=/etc/systemd/system/prometheus-php-fpm-exporter.service.d/group.conf owner=root group=root mode=0644

- name: Update sysconfig - listen address
  lineinfile:
    path: /etc/sysconfig/prometheus-php-fpm-exporter
    regexp: '^PHP_FPM_WEB_LISTEN_ADDRESS='
    line: "PHP_FPM_WEB_LISTEN_ADDRESS={{prometheus_php_fpm_exporter_listen}}:{{prometheus_php_fpm_exporter_firewalld_port}}"

- name: Update sysconfig - scrape uri
  lineinfile:
    path: /etc/sysconfig/prometheus-php-fpm-exporter
    regexp: '^PHP_FPM_SCRAPE_URI='
    line: "PHP_FPM_SCRAPE_URI={{prometheus_php_fpm_exporter_scrape_uri}}"

- name: Ensure systemd sees the service
  systemd: daemon_reload=yes

- name: Add Firewall Zone
  firewalld: zone="{{prometheus_php_fpm_exporter_firewalld_zone}}" state=present permanent=yes

- name: Reload Firewalld
  service: name=firewalld state=reloaded

- name: Add Sources
  firewalld: zone="{{prometheus_php_fpm_exporter_firewalld_zone}}" source="{{item}}" state=enabled permanent=yes immediate=yes
  loop: "{{ prometheus_firewalld_source_ips }}"

- name: Add Ports
  firewalld: zone="{{prometheus_php_fpm_exporter_firewalld_zone}}" port="{{prometheus_php_fpm_exporter_firewalld_port}}/tcp" state=enabled permanent=yes immediate=yes

- name: Enable PHP-FPM status page
  ini_file: dest=/etc/php-fpm.d/www.conf section=www option=pm.status_path value="/status" mode=0644

- name: Enable PHP-FPM status page
  service: name=php-fpm enabled=yes state=restarted

- name: Ensure prometheus-php-fpm-exporter is enabled and started
  service: name=prometheus-php-fpm-exporter enabled=yes state=restarted

