---
- name: Ensure we have noblet-epel.repo
  copy: src=noblet-epel.repo dest=/etc/yum.repos.d/noblet-epel.repo owner=root group=root mode=0644

- name: Install php-fpm-exporter
  yum: name=golang-github-hipages-php-fpm-exporter state=present

- name: Update sysconfig - listen address
  lineinfile:
    path: /etc/sysconfig/prometheus-php-fpm-exporter
    regexp: '^PHP_FPM_WEB_LISTEN_ADDRESS='
    line: "PHP_FPM_WEB_LISTEN_ADDRESS={{prometheus_php_fpm_exporter_listen}}"

- name: Update sysconfig - scrape uri
  lineinfile:
    path: /etc/sysconfig/prometheus-php-fpm-exporter
    regexp: '^PHP_FPM_SCRAPE_URI='
    line: "PHP_FPM_SCRAPE_URI={{prometheus_php_fpm_exporter_scrape_uri}}"

- name: Ensure systemd sees the service
  systemd: daemon_reload=yes

- name: Add Firewall Zone
  firewalld: zone="{{prometheus_php_fpm_exporter_firewalld_zone}}" state=present permanent=yes

- name: Reload Firewalld
  service: name=firewalld state=reloaded

- name: Add Sources
  firewalld: zone="{{prometheus_php_fpm_exporter_firewalld_zone}}" source="{{item}}" state=enabled permanent=yes immediate=yes
  loop: "{{ prometheus_firewalld_source_ips }}"

- name: Add Ports
  firewalld: zone="{{prometheus_php_fpm_exporter_firewalld_zone}}" port="{{prometheus_php_fpm_exporter_firewalld_port}}/tcp" state=enabled permanent=yes immediate=yes

- name: Ensure prometheus-php-fpm-exporter is enabled and started
  service: name=prometheus-php-fpm-exporter enabled=yes state=restarted

