---
symfony_provision_server: apache
symfony_provision_server_user: apache
symfony_provision_db_user: "{{symfony_provision_project_name}}"
symfony_provision_db_name: "{{symfony_provision_project_name}}"
symfony_provision_db_host: localhost
symfony_provision_db_env_credentials: false
symfony_provision_vhosts_dir: /var/www/vhosts
symfony_provision_project_dir: "{{symfony_provision_vhosts_dir}}/{{symfony_provision_project_name}}"
symfony_provision_webroot: "{{symfony_provision_project_dir}}/current/web"

symfony_provision_certifcate: /etc/letsencrypt/live/{{symfony_provision_hostname}}/cert.pem
symfony_provision_key: /etc/letsencrypt/live/{{symfony_provision_hostname}}/privkey.pem
symfony_provision_ca_certs: /etc/letsencrypt/live/{{symfony_provision_hostname}}/chain.pem

symfony_provision_domain: "{{ symfony_provision_hostname.split('.')[1:] | join('.') }}"
