---
- name: Configure fail2ban - firewalldcmd
  template: src="defaults-firewalld.j2" dest="/etc/fail2ban/jail.d/00-defaults.conf" mode=0644 owner=root group=root

- name: Insert ipset rules after blacklist
  template: src="firewallcmd-ipset.conf.j2" dest="/etc/fail2ban/action.d/firewallcmd-ipset.conf" mode=0644 owner=root group=root

