---
- name: Install fail2ban
  yum:
    name: fail2ban
    state: present

- name: Create jail.d
  file: path=/etc/fail2ban/jail.d owner=root group=root mode=755 state=directory

- name: Configure fail2ban - firewalldcmd
  template: src="defaults-firewalld.j2" dest="/etc/fail2ban/jail.d/00-defaults.conf" mode=0644 owner=root group=root

- name: Configure SSHD Ban
  copy: src="ssh-jail.conf"  dest="/etc/fail2ban/jail.d/ssh.conf" mode=0644 owner=root group=root

# - name: Test Apache Existence
#   ansible.builtin.stat: path=/etc/httpd/conf.d get_checksum=false
#   register: fail2ban_apache

# - name: Configure Apache Ban
#   copy: src="apache-jail-404.conf" dest="/etc/fail2ban/jail.d/apache.conf" mode=0644 owner=root group=root
#   when: fail2ban_apache.stat.exists

# - name: Add apache 404 filter
#   copy: src="apache-filter-404.conf" dest="/etc/fail2ban/filter.d/apache-404.conf" mode=0644 owner=root group=root
#   when: fail2ban_apache.stat.exists

# - name: Test nginx Existence
#   ansible.builtin.stat: path=/etc/httpd/conf.d get_checksum=false
#   register: fail2ban_nginx

# - name: Configure nginx Ban
#   copy: src="nginx-jail-404.conf" dest="/etc/fail2ban/jail.d/nginx.conf" mode=0644 owner=root group=root
#   when: fail2ban_nginx.stat.exists

# - name: Add nginx 404 filter
#   copy: src="apache-filter-404.conf" dest="/etc/fail2ban/filter.d/apache-404.conf" mode=0644 owner=root group=root
#   when: fail2ban_nginx.stat.exists

- name: Enable fail2ban
  service: name=fail2ban enabled=yes state=started
  notify: restart fail2ban
