---
- name: Install fail2ban, ipset
  yum: name={{item}} state=present
  with_items:
    - fail2ban
    - ipset

- name: Create jail.d
  file: path=/etc/fail2ban/jail.d owner=root group=root mode=755 state=directory

- name: Configure fail2ban
  template: src="defaults.j2"
    dest="/etc/fail2ban/jail.d/00-defaults.conf" 
    mode=0644
    owner=root
    group=root

- name: Insert ipset rules after blacklist
  copy: src="ipset-proto6.conf" dest="/etc/fail2ban/action.d/iptables-ipset-proto6.conf" mode=0644 owner=root group=root
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

- name: Insert ipset rules after blacklist
  copy: src="firewallcmd-ipset.conf" dest="/etc/fail2ban/action.d/firewallcmd-ipset.conf" mode=0644 owner=root group=root
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7


- name: Disable SSHD-iptables
  copy: src="ssh-iptables.conf" dest="/etc/fail2ban/jail.d/ssh-iptables.conf" mode=0644 owner=root group=root

- name: Configure SSHD-ipset Ban
  template: src="ssh-ipset6.conf.j2"  dest="/etc/fail2ban/jail.d/ssh-ipset.conf" mode=0644 owner=root group=root
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

- name: Configure SSHD-ipset Ban
  template: src="ssh-ipset7.conf.j2"  dest="/etc/fail2ban/jail.d/ssh-ipset.conf" mode=0644 owner=root group=root
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Test VSFTP Existence
  stat: path=/etc/vsftpd get_md5=no
  register: fail2ban_vsftpd

- name: Configure VSFTP-ipset Ban
  template: src="vsftp-ipset.conf.j2"  dest="/etc/fail2ban/jail.d/vsftp-ipset.conf" mode=0644 owner=root group=root
  when: fail2ban_vsftpd.stat.exists

- name: Setup ipset service
  copy: src=ipset.service dest=/etc/systemd/system/ipset.service owner=root group=root mode=0744
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 7

- name: Install initial blacklist
  copy: src=ipset.save dest=/etc/sysconfig/ipset owner=root group=root mode=0744

- name: Enable ipset service
  service: name=ipset enabled=yes
  notify: restart ipset

- name: Enable fail2ban
  service: name=fail2ban enabled=yes
  notify: restart fail2ban
