---
- name: Install golang-prometheus-node-exporter
  yum: name=golang-github-prometheus-node-exporter state=present

- name: Ensure systemd sees the service
  systemd: daemon_reload=yes

- name: Remove Deprecated Firewall Zone
  ansible.builtin.firewalld:
    zone: prometheus-access
    state: absent
    permanent: yes

- name: Allow access through firewall to prometheus exporter port
  ansible.builtin.firewalld:
    zone: "{{prometheus_node_exporter_firewalld_zone}}"
    permanent: true
    immediate: true
    state: enabled
    rich_rule: "rule family=ipv4 source address={{item}} port={{prometheus_node_exporter_firewalld_port}} protocol=tcp"
  loop: "{{ prometheus_firewalld_source_ips }}"

- name: Ensure prometheus-node-exporter is enabled and started
  service: name=prometheus-node-exporter enabled=yes state=started
