---
- name: Ensure httpd is installed
  yum: name=httpd state=present

- name: Enable NameVirtualHosts
  copy: src=virtualhosts.conf dest="/etc/httpd/conf.d/virtualhosts.conf" owner=root group=root mode=644
  when: ansible_distribution_major_version|int == 6

- include: ssl.yml
  when: httpd_include_ssl == true

#- name: Add apache .ssh and .composer directories
#  file: dest="~apache/{{item}}" owner=apache group=apache mode=700
#  with_items:
#    - .ssh
#    - .composer

- name: Ensure httpd is running
  action: service name=httpd state=started

