---
- name: Ensure firewalld is installed
  yum: pkg=firewalld state=present

- name: Ensure firewalld is enabled
  service: name=firewalld state=started enabled=yes

- include_tasks: disable-nftables.yml
- include_tasks: restrict-loopback.yml
- include_tasks: trust-loopback.yml
- include_tasks: disable-forwarding.yml
- include_tasks: disable-icmp-redirects.yml
- include_tasks: disable-source-routing.yml
- include_tasks: ignore-bogus-icmp.yml
- include_tasks: log-martian-packets.yml
- include_tasks: use-reverse-path-filtering.yml
- include_tasks: use-syncookies.yml

- name: Enable ssh access
  firewalld: service=ssh immediate=yes permanent=yes state=enabled
  notify: restart firewalld

- name: Enable default services
  firewalld: service={{ item }} immediate=yes permanent=yes state=enabled
  with_items: '{{firewalld_allowed_services}}'
  notify: restart firewalld

- name: Enable default ports
  firewalld: port={{ item }} immediate=yes permanent=yes state=enabled
  with_items: '{{ firewalld_allowed_ports }}'
  notify: restart firewalld

- name: Configure denied ipsets
  ansible.builtin.template:
     src: ipset-denylist.xml.j2
     dest: /etc/firewalld/ipsets/{{ item.name }}.xml
     owner: root
     group: root
     mode: 0644
  with_items: "{{ firewalld_denied_ips }}"
  notify: restart firewalld

- name: Add ipset to drop zone
  firewalld: source=ipset:{{item.name}} zone=drop immediate=yes permanent=yes state=enabled
  with_items: "{{ firewalld_denied_ips }}"
  notify: restart firewalld

- name: Enable firewalld
  service: name=firewalld enabled=yes
  notify: restart firewalld
