---
- name: Check if wkhtmltopdf is installed
  stat: path=/usr/local/bin/wkhtmltopdf
  register: st_wkhtmltopdf

- name: Download/Install wkhtmltopdf.rpm
  yum: pkg=http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/wkhtmltox-0.12.2.1_linux-centos6-amd64.rpm state=present
  when: not st_wkhtmltopdf.stat.exists

