---
- include: centos6.yml
  when: ansible_distribution_major_version|int == 6

- include: centos7.yml
  when: ansible_distribution_major_version|int == 7 or ansible_distribution_major_version|int >= 23

