---
- name: install elasticsearch rpm gpg key
  rpm_key: state=present key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: install elasticsearch repository
  copy: src=elasticsearch-1.6.repo dest=/etc/yum.repos.d/ owner=root group=root mode=0644

- name: install elasticsearch
  yum: name=elasticsearch state=present

- name: start elasticsearch on boot
  service: name=elasticsearch state=started enabled=yes
