---
- name: install elasticsearch rpm gpg key
  rpm_key: state=present key=https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: install elasticsearch 8.x repository
  copy: src=elasticsearch-8.repo dest=/etc/yum.repos.d/elasticsearch.repo owner=root group=root mode=0644
  when: elasticsearch_version == 8

- name: install elasticsearch and dependencies
  yum: name={{item}} state=latest
  with_items:
    - elasticsearch

- name: start elasticsearch on boot
  service: name=elasticsearch state=started enabled=yes
