---
- name: Ensure haveged is running
  service: name=haveged state=started enabled=yes

- name: Ensure chronyd is running
  service: name=chronyd state=started enabled=yes

- include_tasks: protect-dev-shm.yml
- include_tasks: randomize-mem.yml
- include_tasks: disable-kernel-modules.yml
- include_tasks: systemd.yml
- include_tasks: restrict-dmesg.yml
- include_tasks: restrict-umask.yml
- include_tasks: restrict-user-sessions.yml
- include_tasks: cron.yml
# - include_tasks: harden-sudo.yml
#   when: '"sudo" in ansible_facts.packages'
- include_tasks: password-rules.yml
  when: '"bash" in ansible_facts.packages'
- include_tasks: harden-session.yml
