---
- name: Install Vim
  yum: pkg=vim state=latest

- name: Install Haveged
  yum: pkg=haveged state=latest

- name: Ensure haveged is running
  service: name=haveged state=started enabled=yes

- name: Install Chronyd
  yum: pkg=chrony state=latest

- name: Ensure chronyd is running
  service: name=chronyd state=started enabled=yes

- include_tasks: protect-dev-shm.yml
- include_tasks: randomize-mem.yml
- include_tasks: disable-squashfs.yml
- include_tasks: disable-udf.yml
- include_tasks: disable-usb-storage.yml