---
dependencies:
  - { role: epel, when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 30" }
  - { role: dnf-repos }
  - { role: packages }
  - { role: sshd }
  - { role: aide }
  - { role: firewalld, when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 7" }
  - { role: fail2ban }
  - { role: chrony }
  - { role: selinux, when: "base_selinux_hardening" }
  # - { role: authselect, when: "base_authselect_hardening" }
