---
- include_tasks: php74-centos.yml
  when: php_version == 7.4 and ansible_distribution_major_version|int < 23

- include_tasks: php81-centos.yml
  when: php_version == 8.1 and ansible_distribution_major_version|int < 23

- include_tasks: php83-centos.yml
  when: php_version == 8.3 and ansible_distribution_major_version|int < 23

- name: Install php
  ansible.builtin.dnf:
    state: latest
    name: "{{ item }}"
  loop: "{{ php_packages }}"
  notify:
    - update aide

- name: Install additional php packages
  ansible.builtin.dnf:
    state: latest
    name: "{{ item }}"
  loop: "{{ php_additional_packages }}"
  notify:
    - update aide

- name: PHP datetime
  ini_file: dest=/etc/php.ini section=Date option=date.timezone value="{{php_timezone}}" mode=0644

- name: PHP - Post Max Size
  ini_file: dest=/etc/php.ini section=PHP option=post_max_size value={{php_post_max_size}} mode=0644

- name: PHP - Upload File Size
  ini_file: dest=/etc/php.ini section=PHP option=upload_max_filesize value={{php_upload_max}} mode=0644

- name: PHP - Error Reporting
  ini_file: dest=/etc/php.ini section=PHP option=error_reporting value="{{php_error_reporting}}" mode=0644

- name: PHP - Error log
  ini_file: dest=/etc/php.ini section=PHP option=error_log value=syslog mode=0644

- name: PHP - Display Error
  ini_file: dest=/etc/php.ini section=PHP option=display_error value="{{php_display_errors}}" mode=0644

- name: PHP - Session Divisor
  ini_file: dest=/etc/php.ini section=Session option=session.gc_divisor value="{{php_gc_divisor}}" mode=0644

- name: PHP - Session Probability
  ini_file: dest=/etc/php.ini section=Session option=session.gc_divisor value="{{php_gc_probability}}" mode=0644

- name: PHP - Session Max Lifetime
  ini_file: dest=/etc/php.ini section=Session option=session.gc_max value="{{php_gc_maxlifetime}}" mode=0644

- name: PHP - XLSX/DOCX magic file
  copy: src=magic dest=/etc/magic owner=root group=root mode=0644
