---
- include: php54-centos.yml
  when: php_version == 5.4 and ansible_distribution_major_version|int == 6

- include: php55-centos.yml
  when: php_version == 5.5 and ansible_distribution_major_version|int < 23

- include: php56-centos.yml
  when: php_version == 5.6 and ansible_distribution_major_version|int < 23

- include: php70-centos.yml
  when: php_version == 7.0 and ansible_distribution_major_version|int < 23

- include: php71-centos.yml
  when: php_version == 7.1 and ansible_distribution_major_version|int < 23

- name: Install php
  yum: pkg={{item}} state=latest
  with_items:
    - php
    - php-gd
    - php-intl
    - php-tidy
    - php-pdo
    - php-cli
    - php-process
    - php-xml
    - php-mysql
    - php-mbstring
    - php-bcmath
    - php-pecl-imagick
    - php-pecl-zip
  notify:
    - update aide

- name: Install opcahe 
  yum: pkg=php-opcache state=present
  when: php_version != 5.4

- name: Install PECL opcache
  yum: pkg=php-pecl-opcache state=present
  when: php_version == 5.4

- name: PHP datetime
  ini_file: dest=/etc/php.ini section=Date option=date.timezone value="{{php_timezone}}" mode=0644

- name: PHP - Post Max Size
  ini_file: dest=/etc/php.ini section=PHP option=post_max_size value={{php_post_max_size}} mode=0644

- name: PHP - Upload File Size
  ini_file: dest=/etc/php.ini section=PHP option=upload_max_filesize value={{php_upload_max}} mode=0644

- name: PHP - Error Reporting
  ini_file: dest=/etc/php.ini section=PHP option=error_reporting value="{{php_error_reporting}}" mode=0644

- name: PHP - Error log
  ini_file: dest=/etc/php.ini section=PHP option=error_log value=syslog mode=0644

- name: PHP - Display Error
  ini_file: dest=/etc/php.ini section=PHP option=display_error value="{{php_display_errors}}" mode=0644

- name: PHP - Session Divisor
  ini_file: dest=/etc/php.ini section=Session option=session.gc_divisor value="{{php_gc_divisor}}" mode=0644

- name: PHP - Session Probability
  ini_file: dest=/etc/php.ini section=Session option=session.gc_divisor value="{{php_gc_probability}}" mode=0644

- name: PHP - Session Max Lifetime
  ini_file: dest=/etc/php.ini section=Session option=session.gc_max value="{{php_gc_maxlifetime}}" mode=0644

- name: PHP - XLSX/DOCX magic file
  copy: src=magic dest=/etc/magic owner=root group=root mode=0644
