---
- include_tasks: "centos{{ansible_distribution_major_version}}.yml"
  when: ansible_distribution_major_version|int < 23
    
- include_tasks: fedora.yml
  when: ansible_distribution_major_version|int >= 23

- name: Update root password
  mysql_user: name=root host=localhost password="{{mysql_root_password}}" login_user=root login_password="{{mysql_old_root_password}}"
  when: mysql_old_root_password != False

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: set mysql root password for all root accounts
  mysql_user: name=root host=localhost password="{{mysql_root_password}}"
  ignore_errors: yes

- name: update mysql root password for all root accounts
  mysql_user: name=root password="{{mysql_root_password}}" login_user=root login_password="{{mysql_root_password}}" host_all=yes

- name: ensure anonymous users are not in the database
  mysql_user: name='' state=absent login_user=root login_password="{{mysql_root_password}}" host_all=yes

- name: remove the test database
  mysql_db: name=test state=absent login_user=root login_password="{{mysql_root_password}}" 
