---
- name: Install required packages
  yum: pkg={{item}} state=present
  with_items:
    - rsnapshot
    - rsync

- name: Add rsnapshot-common config
  template: src=common.j2 dest=/etc/rsnapshot-common.conf owner=root group=root mode=644

- name: Setup backup target directory
  file: path=/srv/rsnapshots state=directory owner=root group=root mode=700

- name: Create root SSH public key
  user: name=root generate_ssh_key=yes

- name: Create main directory structure
  file: path="/srv/rsnapshots/{{item.name}}/.sync" recurse=yes state=directory
  with_items: '{{backup_server_configs}}'

- name: Create config
  template: src=rsnapshot.conf.j2 dest="/srv/rsnapshots/{{item.name}}/rsnapshot.conf"
  with_items: '{{backup_server_configs}}'

- name: Add exclude_file.txt
  template: src=exclude.j2 dest="/srv/rsnapshots/{{item.name}}/exclude_file.txt"
  with_items: '{{backup_server_configs}}'

- name: Configure crontab
  template: src=crontab.j2 dest="/etc/cron.d/{{item.name}}-crontab" owner=root group=root mode=644
  with_items: '{{backup_server_configs}}'
  notify:
    - update aide
