- name: Debug
  ansible.builtin.debug:
    msg: "{{item}}"
  with_items: "{{sshd_additional_admins}}"

- name: Create Additional Admin "{{ item.name }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "Admin account for {{ item.name }}"
    groups: wheel
    append: yes
  with_items: "{{sshd_additional_admins}}"

- name: Set up authorized_keys for the configured admin user
  ansible.posix.authorized_key: user="{{ item.0.name }}" state=present key='{{ lookup('file', sshd_key_path + '/' + item.1 ) }}' manage_dir=yes
  with_subelements:
    - "{{sshd_additional_admins}}"
    - public_keys