---
- fail: msg="sshd_key_path needs to be set"
  when: sshd_key_path is not defined

- name: Set up authorized_keys for the root user
  authorized_key: user=root state=present key='{{ lookup('file', sshd_key_path + item) }}' manage_dir=yes
  with_items: '{{sshd_public_keys}}'

#- name: Remove vagrant key
#  authorized_key: user=root state=absent key='{{ lookup('file', sshd_key_path + item) }}' manage_dir=yes
#  with_items:
#    - vagrant

- name: Reconfigure SSH to only allow access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"

- name: Reconfigure SSH to only allow root access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"
  notify:
    - update aide

- name: Enable SSHD
  service: name=sshd enabled=yes
  notify:
    - restart sshd
