---
- fail: msg="sshd_key_path needs to be set"
  when: sshd_key_path is not defined

- name: Set up authorized_keys for the configured admin user
  authorized_key: user="{{sshd_admin_user}}" state=present key='{{ lookup('file', sshd_key_path + item) }}' manage_dir=yes
  with_items: '{{sshd_public_keys}}'

- name: Reconfigure SSH to only allow access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"

- name: Reconfigure SSH to only allow root access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"
  when: sshd_allow_root
  notify:
    - update aide

- name: Enable SSHD
  service: name=sshd enabled=yes
  notify:
    - restart sshd

- include_tasks: configure-additional-admins.yml
  when: sshd_additional_admins | length | int > 0

- include_tasks: disable-empty-pass.yml
- include_tasks: disable-host-auth.yml
- include_tasks: disable-rhosts.yml
- include_tasks: disallow-env-override.yml
- include_tasks: disable-user-known-hosts.yml
- include_tasks: disable-x11-forwarding.yml
- include_tasks: disable-remote-x11-connect.yml
- include_tasks: login-grace-time.yml
- include_tasks: max-client.yml
- include_tasks: max-auth-tries.yml
- include_tasks: max-sessions.yml
- include_tasks: max-start-ups.yml
- include_tasks: verbose-logging.yml
- include_tasks: disable-extra-auth.yml
# - include_tasks: client-alive.yml
- include_tasks: delay-compression.yml
- include_tasks: use-priv-separation.yml
- include_tasks: frequent-key-regen.yml
- include_tasks: print-last-log.yml
- include_tasks: enable-strict-mode-checking.yml
