---
- name: Set up authorized_keys for the root user
  authorized_key: user=root state=present key="{{ item }}" manage_dir=yes
  with_file: sshd_public_keys

- name: Remove vagrant key
  authorized_key: user=root state=absent key="{{ item }}" manage_dir=yes
  with_file:
    - vagrant

- name: Reconfigure SSH to only allow access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"

- name: Reconfigure SSH to only allow root access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"
  notify:
    - update aide

- name: Enable SSHD
  service: name=sshd enabled=yes
  notify:
    - restart sshd
