---
- fail: msg="sshd_key_path needs to be set"
  when: sshd_key_path is not defined

- name: Set up authorized_keys for the configured admin user user
  authorized_key: user="{{sshd_admin_user}}" state=present key='{{ lookup('file', sshd_key_path + item) }}' manage_dir=yes
  with_items: '{{sshd_public_keys}}'

- name: Reconfigure SSH to only allow access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"

- name: Reconfigure SSH to only allow root access using key-based authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?PermitRootLogin" line="PermitRootLogin without-password"
  when: sshd_allow_root
  notify:
    - update aide

- name: Enable SSHD
  service: name=sshd enabled=yes
  notify:
    - restart sshd

- include_tasks: disable-empty-pass.yml
- include_tasks: disable-host-auth.yml
- include_tasks: disable-rhosts.yml
- include_tasks: disallow-env-override.yml
- include_tasks: login-grace-time.yml
- include_tasks: max-client.yml
- include_tasks: max-auth-tries.yml
- include_tasks: max-sessions.yml
- include_tasks: max-start-ups.yml